// #include <pybind11/pybind11.h>
#include <torch/extension.h>

// Include your shared headers
#include "../shared/board.h"
#include "../shared/chinese_checkers.h"
#include "../shared/constants.h"

// Wrap your existing function
torch::Tensor init_state_batched_wrap(int64_t n_batch) {
    return initialize_state_batched((int)n_batch);
}

torch::Tensor get_action_mask_batched_wrap(torch::Tensor game_state_batch) {
    // this is the risk, that the game_state_batch becomes non-contiguous
    auto n_batch = game_state_batch.size(0);
    return get_action_mask_batched(game_state_batch.data_ptr<int>(), (int)n_batch);
}

int64_t update_state_batched_wrap(torch::Tensor game_state_batch, torch::Tensor moves_batch) {
    // this is generated by Python code, so it's not necessarily contiguous (e.g. output of a network)
    moves_batch = moves_batch.contiguous();
    auto n_batch = game_state_batch.size(0);
    update_state_batched(game_state_batch.data_ptr<int>(), moves_batch.data_ptr<int>(), (int)n_batch);
    return 0;
}

// Create the PyBind entry point
PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("initialize_state_batched", &init_state_batched_wrap, "Initialize board states (CPU)");
    m.def("get_action_mask_batched", &get_action_mask_batched_wrap, "Get action mask for batched states (CPU)");
    m.def("update_state_batched", &update_state_batched_wrap, "Update board states (CPU)");
}

// Optionally register a custom op
TORCH_LIBRARY(chinese_checkers_ext, m) {
    m.def("initialize_state_batched(int n_batch) -> Tensor");
    m.def("get_action_mask_batched(Tensor game_state_batch) -> Tensor");
    m.def("update_state_batched(Tensor game_state_batch, Tensor moves_batch) -> int");
}

TORCH_LIBRARY_IMPL(chinese_checkers_ext, CPU, m) {
    m.impl("initialize_state_batched", &init_state_batched_wrap);
    m.impl("get_action_mask_batched", &get_action_mask_batched_wrap);
    m.impl("update_state_batched", &update_state_batched_wrap);
}